### ISSUE TITLE
Create modules documentation

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/ergocub-software#100]
We're required to create the modules documentation hosted via GH Pages relying on `doxygen`.
In particular, `ergoCubEmotions` API will be available therein.

Useful resources:
- https://github.com/robotology/how-to-document-modules

**Comment by Nicogene** [comment]
A first version of the documentation has been added by:

- #124 
- #125 

![immagine](https://github.com/icub-tech-iit/ergocub-software/assets/19152494/356356e4-63f6-4371-b9e7-cfa690008fbb)

Thanks heaps @martinaxgloria 🎖️ 

Closing.
