### ISSUE TITLE
New expressions

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/ergocub-software#104]
Hi @martinaxgloria 

Could you please update the expressions we have with the latest ones we received from the designers, which are better centered with respect to the whole face?
Here's the latest delivery: [**`expressions.zip`**](https://github.com/icub-tech-iit/ergocub-software/files/11404779/expressions.zip).

Be careful, the correct tag for one expression is `alert` and not `angry`[^1]. Thus, you'd need to update the config.ini file too.

cc @Nicogene @maggia80 

[^1]: The attached archive already contains the correct tags.

**Comment by martinaxgloria** [comment]
Hi @pattacini,

yes, I'm already doing all the necessary changes to the module

**Comment by martinaxgloria** [comment]
PR here:

- https://github.com/icub-tech-iit/ergocub-software/pull/105

cc @pattacini @Nicogene

**Comment by pattacini** [comment]
Reopening just because we'd need a video of the latest expressions running on the robot for comparison purposes, as we aim to get the final @maggia80's approval on that.

**Comment by martinaxgloria** [comment]
Today, during the demo session, I took this video in order to check the last version of the facial expressions:

https://github.com/icub-tech-iit/ergocub-software/assets/114698424/3f407843-ac58-4574-a0be-9b8d7a599486

Talking with @maggia80 and @pattacini, we noticed that the videos are not exactly centered on the OLED and maybe we can ask to move up the expressions a little bit more. For the first issue, I will check it more in detail by using one of the expressions with a centered line and then we can send the request to the designers.

**Comment by martinaxgloria** [comment]
As expected and as you can see from the photo below, the expressions are not centered at all (the white line is not aligned with the "middle" of the mask)


![photo_5967431268075420245_y](https://github.com/icub-tech-iit/ergocub-software/assets/114698424/20bb1e93-b7e2-4759-9774-0695015fdaa6)


cc @pattacini @maggia80 @Nicogene

**Comment by pattacini** [comment]
Well done @martinaxgloria 👍🏻 
We need a way to convey the following info to the designers:
1. We need to move the expressions even further up.
2. We need to center the expressions in the middle of the face.Well done @martinaxgloria 👍🏻 
We need a way to convey the following info to the designers:
1. We need to move the expressions even further up.
2. We need to center the expressions in the middle of the face.

To achieve 1 and 2, one possibility is that we stick to one particular expression (the one above is the best, is it `alert`?) and:
1. Draw a horizontal line that meets our requirements: i.e., identify on the robot where the biggest eye should be tangential to that line.
2.  Draw a vertical line that meets the center of the face. With trial and error, you could move the bar further right until the point it is aligned with the groove in the cover.

After a quick internal review, the designer will receive this expression with the two bars and will adjust all the expressions accordingly.

To achieve 1 and 2, one possibility is that we stick to one particular expression (the one above is the best, is it `alert`?) and:
1. Draw a horizontal line that meets our requirements: i.e., identify on the robot where the biggest eye should be tangential to that line.
2.  Draw a vertical line that meets the center of the face. With trial and error, you could move the bar further right until the point it is aligned with the groove in the cover.

After a quick internal review, the designer will receive this expression with the two bars and will adjust all the expressions accordingly.

**Comment by pattacini** [comment]
Lovely!
I think we can proceed indeed!
The horizontal bar should be the limit of the right eye's shade.

**Comment by martinaxgloria** [comment]
> The horizontal bar should be the limit of the right eye's shade.

Yes, we ask to take this expression as reference and then to adapt the others

**Comment by pattacini** [comment]
Here's the reference image: 

![reference](https://github.com/icub-tech-iit/ergocub-software/assets/3738070/502ede42-e8e9-4a4c-a8a6-e48f9ab7a71e)

@martinaxgloria sent out the email 📧 
We can close this!
