### ISSUE TITLE
[ergoCubSN000] Different ft sensor names between URDF file and yarprobotinterface configuration files

### ISSUE THREAD

**Issue by isorrentino** [icub-tech-iit/ergocub-software#165]
## Task description
With the [latest release](https://github.com/icub-tech-iit/ergocub-software/releases/tag/v0.3.4) of `ergocub-software` the robot does not start because of an error from `whole-body-dynamics` about the ft sensors (sorry I do not have the message of the error to attach here).

Checking the URDF file of `ergoCubSN000`, I discovered that two duplicated fixed joints are associated with each ft. 

See https://github.com/icub-tech-iit/ergocub-software/blob/d82ce6a3933e64b61a485959d8cb6305f277ac4a/urdf/ergoCub/robots/ergoCubSN000/model.urdf#L906-L940.

cc @traversaro @Nicogene @SimoneMic

**Comment by traversaro** [comment]
This seems a regression of https://github.com/icub-tech-iit/ergocub-software/pull/159, that was triggered by https://github.com/icub-tech-iit/ergocub-software/pull/158 .

**Comment by traversaro** [comment]
Looking more at this, it seems that it should be ok:
* `r_arm_ft_sensor` is the joint actually corresponding to the FT sensor
* `r_arm_ft_fixed_joint` is a joint that connects the "fake link" (i.e. additional frame) `r_arm_ft`, that is used on RViz to visualize the reading of the `r_arm_ft` sensor.

Clearly the naming of `r_arm_ft_fixed_joint` is not ideal, but it should work fine. What kind of errors are you seeing with this model?

**Comment by Nicogene** [comment]
I think that the error @isorrentino is having is due to the fact that on the real robot we have different sensor names.

It is related to https://github.com/icub-tech-iit/ergocub-software/issues/156.
I am afraid that until #156 is not fixed the real robot and the simulated one need 2 different wbd configuration files.

**Comment by isorrentino** [comment]
I'm not on the robot, but at this point I think the problem is the one specified by @Nicogene. The names do not match and WBD fails.

**Comment by traversaro** [comment]
> I am afraid that until #156 is not fixed the real robot and the simulated one need 2 different wbd configuration files.

I think there are two different problems here. One are YARP devices names, and another are FT sensors names. For both consistency between simulated and real robot is important, but the latter is more important as it involves names specified in URDF that are harder to change.

**Comment by traversaro** [comment]
@isorrentino @Nicogene based on your comments I modified the issue name.

**Comment by Nicogene** [comment]
> > I am afraid that until #156 is not fixed the real robot and the simulated one need 2 different wbd configuration files.
> 
> I think there are two different problems here. One are YARP devices names, and another are FT sensors names. For both consistency between simulated and real robot is important, but the latter is more important as it involves names specified in URDF that are harder to change.

In this sense for iCub* i set the `frameName` parameter in order to match the name in the urdf: https://github.com/robotology/robots-configuration/blob/edc514623e39330540aecb500d75ecac3874f7bc/iCubGenova11/hardware/FT/right_arm-eb3-j0_3-strain.xml#L34

**Comment by traversaro** [comment]
> > > I am afraid that until #156 is not fixed the real robot and the simulated one need 2 different wbd configuration files.
> > 
> > 
> > I think there are two different problems here. One are YARP devices names, and another are FT sensors names. For both consistency between simulated and real robot is important, but the latter is more important as it involves names specified in URDF that are harder to change.
> 
> In this sense for iCub* i set the `framename` parameter in order to match the name in the urdf: https://github.com/robotology/robots-configuration/blob/edc514623e39330540aecb500d75ecac3874f7bc/iCubGenova11/hardware/FT/right_arm-eb3-j0_3-strain.xml#L34

That would not solve the problem. The problem here are the sensor names (i.e. the `name` attribute of the `sensor` tag), not the frame names.

**Comment by Nicogene** [comment]
> > Probably we need to agree on what the sensor name for the FT sensor should before proceeding with [robotology/robots-configuration#561](https://github.com/robotology/robots-configuration/pull/561) .
> 
> See [robotology/icub-models-generator#240 (comment)](https://github.com/robotology/icub-models-generator/pull/240#issuecomment-1604172317) , in particular the comment:
> 
> > Requires changes in icub-model-generator, ergocub-software, robots-configuration. If the changes are not done together, wholebodydynamics from whole-body-estimators stop working.
> 
> Looking at the situaton now, it seems that #158 basically went ahead with O1 for ergocub-software, so as there was no other input, I suggest to proceed with O1 to fix the situation on ergocub and permit people to use the robot.
> 
> See also [robotology/icub-models-generator#242](https://github.com/robotology/icub-models-generator/issues/242) .

I agree!

**Comment by traversaro** [comment]
I think so, @isorrentino do you confirm?

**Comment by isorrentino** [comment]
Yes, I confirm. Feel free to close the issue.
