### ISSUE TITLE
Discrepancy between documented and simulated limits for ergoCub hand MK5

### ISSUE THREAD

**Issue by xEnVrE** [icub-tech-iit/ergocub-software#168]
After the recent update of the documentation in https://icub-tech-iit.github.io/documentation/hands/hands_mk5/#mk50, I noticed that there might be problems with some of the limits.

For example, the thumb proximal has 90 degrees as limit:

![image](https://github.com/icub-tech-iit/ergocub-software/assets/6014499/e5e116ea-00e1-4466-a627-599b0e6aa2df)

The current configuration file, instead (check the second column)

https://github.com/icub-tech-iit/ergocub-software/blob/5ca85d3b065f47ea652bb413d9b0536f5dfcc72c/urdf/ergoCub/conf/gazebo_ergocub_left_hand.ini#L13

has 82.1 degrees.

Although we could just update the configuration file with the documentation, I am not really sure whether they are correct. Indeed, I remember, while looking at it in the CAD with @Lawproto, that the thumb proximal could not really reach 90 degrees but a little less, speaking from the mechanical point of view.

cc @Lawproto @traversaro

**Comment by Lawproto** [comment]
@xEnVrE you are right, I confirm.

![immagine](https://github.com/icub-tech-iit/ergocub-software/assets/84333301/25111e42-79a1-433d-a700-b49abf51eac6)

**Comment by Lawproto** [comment]
@xEnVrE pull request opened. 
https://github.com/icub-tech-iit/documentation/pull/304

**Comment by xEnVrE** [comment]
Thanks @Lawproto

**Comment by Lawproto** [comment]
@xEnVrE you are welcome. The pull request was merged, now you can see the correct value in the documentation.

![immagine](https://github.com/icub-tech-iit/ergocub-software/assets/84333301/7031e3cd-471b-4546-8173-9b6e534218af)

**Comment by xEnVrE** [comment]
Thanks @Lawproto.

As discussed f2f with @Lawproto, when the PR was opened I did not already notice that also the `l_thumb_dist` is different between the two sources:
- `53.6` within the config file
- `59.2` within the documentation

Would it be possible to also verify this?

**Note: all the other numbers are correct!**

**Comment by Lawproto** [comment]
@xEnVrE from the CAD model, I say the config file is right.

![immagine](https://github.com/icub-tech-iit/ergocub-software/assets/84333301/69cbaf43-77e9-4d23-8fac-ad949806742b)

I opened ad PR: https://github.com/icub-tech-iit/documentation/pull/305.

**Comment by xEnVrE** [comment]
Thanks heaps @Lawproto

**Comment by xEnVrE** [comment]
Closing as the issue has been solved.
