### ISSUE TITLE
Automatic indent urdf file after generation

### ISSUE THREAD

**Issue by GiulioRomualdi** [icub-tech-iit/ergocub-software#170]
## Task description
It would be nice to automatically indent the urdf file at the end of the generation. This will simplify the manual inspection of the model of the robot from file.

## Definition of Done
A procedure to automatically indent the file once generated (or at the end of the generation)

cc @traversaro

**Comment by traversaro** [comment]
Probably we can just run one of the following command as part of the generation process: https://stackoverflow.com/questions/16090869/how-to-pretty-print-xml-from-the-command-line .

**Comment by traversaro** [comment]
If we want to do that as part of creo2urdf/idyntree, the function used by `xmllint --format` is `xmlSaveFormatFileEnc`, see https://github.com/GNOME/libxml2/blob/99cba4b37b1a39d477f1b5acf782c6bd2d16d0ee/xmllint.c#L2619C10-L2619C30 .

**Comment by Nicogene** [comment]
Looking at the [`libxml2` doc](https://gnome.pages.gitlab.gnome.org/libxml2/devhelp/libxml2-tree.html) I found this solution.

- https://github.com/icub-tech-iit/creo2urdf/pull/54

See the resulting urdfs:

- https://github.com/icub-tech-iit/ergocub-software/pull/171
