### ISSUE TITLE
Clarification on the zero configuration of *_index_add of the simulated Mk5.1 hand

### ISSUE THREAD

**Issue by xEnVrE** [icub-tech-iit/ergocub-software#172]
I am opening this to ask a clarification about the behavior of the `*_index_add` joint of the Mk5 **.1** hand.

According to [this](https://github.com/icub-tech-iit/ergocub-design-lowerarm/issues/157#issuecomment-1660566060) comment, it was decided that the zero position of the index adduction is the one where the index is more distant from the other fingers, i.e.:

<img src="https://github.com/icub-tech-iit/ergocub-software/assets/6014499/7c21376e-ff90-4709-9160-22fe02b38a2d" height=200/>

It seems that such new behavior has not been transferred correctly in the simulation:

### index_add = 0

<img src="https://github.com/icub-tech-iit/ergocub-software/assets/6014499/a645b1f8-6634-40ef-ad6e-b61b7cf77976" height=200/>

### index_add = 15

<img src="https://github.com/icub-tech-iit/ergocub-software/assets/6014499/b6477dfb-e8f8-4662-a8c8-132baad06bde" height=200/>

I guess we should:
- invert the direction of the axis of rotation
- change the default configuration at startup in Gazebo

cc @Nicogene @pattacini @fiorisi

**Comment by pattacini** [comment]
Good catch @xEnVrE 👍🏻 

@Nicogene @mfussi66 please read up on the issue from https://github.com/icub-tech-iit/ergocub-design-lowerarm/issues/157#issuecomment-1660679203 onward for more info on that.

You were off, I tried to find out why we ended up with a different convention wrt the iCub hand but unsuccessfully. At this point, we ought to conform to the latest convention.

**Comment by Nicogene** [comment]
Since creo2urdf assumes that in the simulation model, all the joints are in their zeros, I need that @Mick3Lozzo or @Lawproto to change the rest position of the `index_add` joints in the simulation model.

What about the `thumb_add` ? Also that has to be changed?

**Comment by xEnVrE** [comment]
> Or actually, maybe it is the chance for changing the range to -3 to 12 degrees

I am a bit confused, isn't it an issue related to Mk5.0?

> What about the thumb_add ? Also that has to be changed?

I would say no, but others might comment on this. The behavior of the thumb adduction is at the moment similar to that on the old iCub hands, i.e. 0.0 -> thumb within the plane of the palm, max -> thumb ~orthogonal to the palm or the like

**Comment by pattacini** [comment]
>Since creo2urdf assumes that in the simulation model, all the joints are in their zeros, I need that @Mick3Lozzo or @Lawproto to change the rest position of the index_add joints in the simulation model.

Let's do it.

**Comment by Lawproto** [comment]
@Nicogene @pattacini to sum it up, I inderstood I have to update the ergoCub 1.1 sim model with the new index position.

![immagine](https://github.com/icub-tech-iit/ergocub-software/assets/84333301/b9f9af93-cca7-464c-a12a-76b5aec9ccef)

It this is the case, the `index_add` joint rom spans from 0 (figure) to 15°.

**Comment by pattacini** [comment]
Yep 👍🏻

**Comment by Nicogene** [comment]
After @Lawproto fix, here is the PR that port those changes in the urdf:

- https://github.com/icub-tech-iit/ergocub-software/pull/173

### 0 deg
![immagine](https://github.com/icub-tech-iit/ergocub-software/assets/19152494/afd837d1-b959-4347-bc54-68f4f6706b74)
### 15 deg
![immagine](https://github.com/icub-tech-iit/ergocub-software/assets/19152494/0a9f83e0-5219-4c24-a7e8-998da276bd00)


cc @fiorisi @pattacini @xEnVrE
