### ISSUE TITLE
Discuss RealSense rgb / depth frames and alignment in simulation

### ISSUE THREAD

**Issue by xEnVrE** [icub-tech-iit/ergocub-software#183]
I was trying to visualize the point cloud from `ergoCub1_1` in simulation with `rviz2` and I was superimposing it on the 3D model of the robot rendered according to the forward kinematics and I noticed the following misalignment:

![image](https://github.com/icub-tech-iit/ergocub-software/assets/6014499/f7e76539-c7de-426b-8ad2-9ee8eae9d09d)

As the red arrows try to indicate, the point cloud is **not** perfectly superimposed on the model - something that 1) I was not expecting and that 2) actually does not happen on other robots, e.g., `iCubGazeboV2_5_visuomanip`.

### URDF investigation

I then investigated the `urdf` of the robot `ergoCubGazeboV1_1` and I noticed the following facts:
- a `realsense` frame is defined and two childs
  - `realsense_depth_frame`
  - `realsense_rgb_frame`
  via two fixed joints
- the way the RGB camera plugin is configured is not really clear to be honest:
    - the sensor is referring to the link `realsense` instead of `realsense_rgb_frame`
  https://github.com/icub-tech-iit/ergocub-software/blob/a092c3a53ab2ab8c9e46bd0a4210ee8815cbaf52/urdf/ergoCub/robots/ergoCubGazeboV1_1/model.urdf#L3488
    - the pose of the sensor is changed in other two places (3492, 3494)
  https://github.com/icub-tech-iit/ergocub-software/blob/a092c3a53ab2ab8c9e46bd0a4210ee8815cbaf52/urdf/ergoCub/robots/ergoCubGazeboV1_1/model.urdf#L3492-L3495
    - an additional pose reference is given later on
  https://github.com/icub-tech-iit/ergocub-software/blob/a092c3a53ab2ab8c9e46bd0a4210ee8815cbaf52/urdf/ergoCub/robots/ergoCubGazeboV1_1/model.urdf#L3520-L3523
   - all these transformation makes it quite hard to understand what is going on
- the depth camera is configured similarly but with **different numbers**

### Proposed changes

I propose the following changes:
- (I know that not all might agree on that) we should make sure that the RGB and depth sensors are configured to produce perfectly aligned frames. Even if the simulator can handle two different frames for the RGB and depth parts, as the real camera has a shift between the two, the final aim of the simulator should be that of reproducing a real setup and on the real setup we always, not sure if someone does not, activate the alignment between RGB and depth frames at the YARP-level or ROS2-level, i.e. the final images on ports/topic are already aligned.
- simplify a lot the way the sensors are configured in the URDF by making these changes:
  - make sure that both the RGB and depth sensors refer to the frame `realsense_rgb_frame`
  - removing all the other change of poses
  - keep only the `<pose>0.0 0.0 0.0 0.0 -1.57 1.57</pose>` correction which make sure that the usual orientation used for cameras in robotics (y down, x right, z out of image plane) is aligned with the convention used inside Gazebo (z up, y left, x out of image plane)

The final configuration becomes:
```console
<gazebo reference="realsense_rgb_frame">
    <sensor name="realsense_head_depth" type="depth">
      <always_on>1</always_on>
      <update_rate>30.000000</update_rate>
      <pose>0.0 0.0 0.0 0.0 -1.57 1.57</pose>
      <camera name="intel_realsense_depth_camera">
      (etc)
  </gazebo>
  <gazebo reference="realsense_rgb_frame">
    <sensor name="realsense_head_rgb" type="camera">
      <always_on>1</always_on>
      <update_rate>30.000000</update_rate>
      <pose>0.0 0.0 0.0 0.0 -1.57 1.57</pose>
      (etc)
  </gazebo>
```

### Comparison

Using the above proposals, we get the alignment as expected:

![image](https://github.com/icub-tech-iit/ergocub-software/assets/6014499/52357a7c-53b5-4ff6-aed3-183bf8b8876b)

Superimposition is quite nice also when closing fingers:

<img src="https://github.com/icub-tech-iit/ergocub-software/assets/6014499/b3f7a01e-c8cd-4d57-b8c7-53e85d9a0e20" height=400/>

#

I would be happy to discuss on the above with you in order to understand how to possibly fix the configuration for Gazebo, keeping in mind that there is a part of automatic generation going on in this repository.

cc @traversaro @pattacini @Nicogene

**Comment by traversaro** [comment]
> the way the RGB camera plugin is configured is not really clear to be honest:

I think I can help a bit on this:


> the sensor is referring to the link realsense instead of realsense_rgb_frame

`realsense_rgb_frame` is not a real frame with a mass, it is just an additional mass-less links used in URDF to represent a frame. It is lumped away in the URDF --> SDF conversion, i.e. removed. The `<model>--><gazebo>` `reference` attribute require that a "real" link (or joint) is passed as argument.

> an additional pose reference is given later on

You can ignore that tags. `<model>--><sensor>` tags in URDF are ignored by Gazebo/SDF, that only considers `<model>--><gazebo>--><sensor>` tags. The `<model>--><sensor>` tags are part of an URDF extension that was never implemented by sdformat/Gazebo: http://wiki.ros.org/urdf/XML/sensor .

**Comment by traversaro** [comment]
> The `<model>--><gazebo>` `reference` attribute require that a "real" link (or joint) is passed as argument (unless you are using a really recent version of sdformat, if I am not wrong).

Just to elaborate more on this, which version of Gazebo and sdformat you used for your tests?

**Comment by pattacini** [comment]
To be addressed after our PI16, that is in two weeks.

/remind October 30 cc @Nicogene

**Comment by traversaro** [comment]
> * Even if the simulator can handle two different frames for the RGB and depth parts, as the real camera has a shift between the two, the final aim of the simulator should be that of reproducing a real setup and on the real setup we always, not sure if someone does not, activate the alignment between RGB and depth frames at the YARP-level or ROS2-level, i.e. the final images on ports/topic are already aligned.

Related to that, we should check which configuration files we ship by default to access the realsense and what is set there.

**Comment by xEnVrE** [comment]
Thanks @traversaro and @pattacini for your answers.

I did not know that the frame used in the `reference` tag had to be "real". If `realsense_rgb_frame` gets lumped away, it is then strange that I was able to run the simulation with `reference = realsense_rgb_frame`. But, as you said, maybe it depends on the version of `gazebo` and `sdf`.

> Just to elaborate more on this, which version of Gazebo and sdformat you used for your tests?

I am using
- `Gazebo multi-robot simulator, version 11.13.0` (the apt package is `gazebo11/unknown,now 11.13.0-1~focal amd64 [installed]`
- the sdf of the world where I put `ergoCubGazeboV1_1` had `sdf version="1.7"` within the xml
- I am composing the point cloud in` YARP` and then sending it to `ROS2` with a custom module. That module is using the frame `realsense_rgb_frame` to tag the point cloud - this tag is then used within `rviz2` to properly place the cloud in the space
  > this seems consistent with the configuration done for the RGBD sensors on ROS2 in simulation, see:

  https://github.com/icub-tech-iit/ergocub-software/blob/a092c3a53ab2ab8c9e46bd0a4210ee8815cbaf52/urdf/ergoCub/conf/sensors/rgbd_camera_wrapper_ros2.xml#L9

> Related to that, we should check which configuration files we ship by default to access the realsense and what is set there.

In simulation, it seems that the alignment was assumed, i.e.:
https://github.com/icub-tech-iit/ergocub-software/blob/a092c3a53ab2ab8c9e46bd0a4210ee8815cbaf52/urdf/ergoCub/conf/sensors/rgbd_camera_wrapper_ros2.xml#L9-L10

On the real robot, it seems that the alignment is enabled as well:
https://github.com/robotology/robots-configuration/blob/master/ergoCubSN001/sensors/realsense.xml#L12

**Comment by xEnVrE** [comment]
> Actually I was just relying on memory, and I could not find anything on this, so I may be not recalling correctly. If attaching to a fake link works fine on the Gazebo available via apt on Ubuntu 22.04 (i.e. sdformat9 9.7.0/Gazebo 11.10.2), it is ok for me.

actually this test was done on Ubuntu 20.04 but we also have an easy way to test it on Ubuntu 22.04 so that we can be sure

**Comment by xEnVrE** [comment]
> If attaching to a fake link works fine on the Gazebo available via apt on Ubuntu 22.04

I tried with Ubuntu 22.04 with Gazebo 11.0.2 and your suspicions were correct @traversaro: using a fake link as a reference tag does **not** work (the image was badly rotated).

Nonetheless, the actual problem is more the fact that vision and kinematics do not agree - as the point cloud reveals.

In this regard, I tried to restore the original URDF and then use the same pose parameters of the RGB sensor, i.e.,
https://github.com/icub-tech-iit/ergocub-software/blob/a092c3a53ab2ab8c9e46bd0a4210ee8815cbaf52/urdf/ergoCub/robots/ergoCubGazeboV1_1/model.urdf#L3492-L3495

for the depth sensor and that was enough to **solve** the problem.

**Comment by traversaro** [comment]
Thanks! Yes, the two problems (that the sensor stuff is complex, and that the RGB and the depth are not aligned while in reality they are) are distinct. I think we can keep the issue to track the second problem.

**Comment by xEnVrE** [comment]
> In this regard, I tried to restore the original URDF and then use the same pose parameters of the RGB sensor

I forgot to mention that maybe also the `<horizontal_fov>` tags should be matched so as to have the same intrinsics on both sensors.

**Comment by Nicogene** [comment]
Hi @xEnVrE,

Since in the urdf there is not a single sensor that handles both streams, but depth and rgb are disjointed sensors, a way to align it could be take this
https://github.com/icub-tech-iit/ergocub-software/blob/f7ba46bb2a6a9aa94f0402916b7a2288a6d9cd84/urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options.yaml#L817-L851
Changing `frameName` to `SCSYS_HEAD_RGB` and `<horizontal_fov>1.57079</horizontal_fov>` to `<horizontal_fov>1.2217</horizontal_fov>` should mimic what happens on the real robot.
About the `pose` 
https://github.com/icub-tech-iit/ergocub-software/blob/f7ba46bb2a6a9aa94f0402916b7a2288a6d9cd84/urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options.yaml#L825

I probably copied it from icub3 yaml so it can be wrong but I don't think it is the problem here.

**Comment by xEnVrE** [comment]
> I probably copied it from icub3 yaml so it can be wrong but I don't think it is the problem here.

Maybe I am wrong, but should not we have the same pose for both sensors to get the alignment? Otherwise they will observe a different scene.

**Comment by Nicogene** [comment]
> but should not we have the same pose for both sensors to get the alignment?

If I am not wrong that pose is referred to the `frameName`, it is already the same for the 2 sensors, so changing the frame could do the trick

I committed here https://github.com/icub-tech-iit/ergocub-software/tree/fix/depthAlignment the urdf of ergoCubGazeboV1_1 w/ the depth aligned w/ the rgb camera, if it is correct I do the same thing also for the other robots and open a PR

**Comment by xEnVrE** [comment]
> if it is correct I do the same thing also for the other robots and open a PR

I can make some tests and let you know between today and tomorrow

**Comment by xEnVrE** [comment]
Hi @Nicogene, 

I tested your branch and the result seems fine so far:

![image](https://github.com/icub-tech-iit/ergocub-software/assets/6014499/bb7d5e72-6efa-4eae-a810-c6b7006116da)

**Comment by Nicogene** [comment]
PR opened:

- https://github.com/icub-tech-iit/ergocub-software/pull/188
