### ISSUE TITLE
`ErgoCubGazeboV1_minContacts`: Collisions positions

### ISSUE THREAD

**Issue by flferretti** [icub-tech-iit/ergocub-software#184]
## Task description

When working with `ErgoCubGazeboV1_minContacts` and `ErgoCubGazeboV1_1_minContacts` downloaded from the robotology channel with `conda`, I noticed that the box collisions on the feet were not below or matching the soles as expected. (See image below)

![MicrosoftTeams-image](https://github.com/icub-tech-iit/ergocub-software/assets/102977828/c5931cfd-6c40-43dd-a099-669f57f8eda3)

I was then wondering if this were the expected result or if the offset needs to be changed.

Package version:
```console
ergocub-software          0.4.0              h59595ed_101    robotology
```

C.C. @lrapetti @CarlottaSartore

**Comment by traversaro** [comment]
Which version of ergocub software did you install?

**Comment by traversaro** [comment]
This seems similar to https://github.com/icub-tech-iit/ergocub-software/issues/174 , that was fixed in master, perhaps we could do a release of ergocub-software to release the fix? @Nicogene

**Comment by flferretti** [comment]
> This seems similar to #174 , that was fixed in master, perhaps we could do a release of ergocub-software to release the fix? @Nicogene

Yes, in the latest URDF version the problem has been solved. Thanks

**Comment by Nicogene** [comment]
Release done:
- https://github.com/icub-tech-iit/ergocub-software/releases/tag/v0.5.0

**Comment by flferretti** [comment]
Thank you all, closing

**Comment by traversaro** [comment]
Thanks! Unfortunately at the moment ergocub-software is not on conda-forge so it will take a few days to get the new package in the robotology channel.

**Comment by traversaro** [comment]
Update packages are available in robotology channel: https://anaconda.org/robotology/ergocub-software  (except for Windows that have some problems).
