### ISSUE TITLE
ergocubSN000 has wrong names for l_upper_arm and r_upper_arm

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/ergocub-software#197]
As of https://github.com/icub-tech-iit/ergocub-software/commit/4a1ad6b550c7cf3e481933dfc915036deae5c9b0, the wrong link names l_upperarm and r_upperarm are used instead (see https://icub-tech-iit.github.io/documentation/icub_kinematics/icub-model-naming-conventions/icub-model-naming-conventions/ for the reference on the convention for which they should be l_upper_arm, r_upper_arm.

**Comment by Nicogene** [comment]
PR:

- https://github.com/icub-tech-iit/ergocub-software/pull/198
