### ISSUE TITLE
[ergoCubSN001] Disable FT sensors in URDF

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/ergocub-software#200]
## Task description
Following up on https://github.com/robotology/robots-configuration/pull/598#issuecomment-1841606958, we're requested to update the URDF of ergoCubSN001 to disable the FT sensors.

## Definition of Done
- URDF modified accordingly
- URDF tested in simulation

cc @Nicogene @GiulioRomualdi

**Comment by Nicogene** [comment]
The arms FTs seems already there:

https://github.com/icub-tech-iit/ergocub-software/blob/54e090910392177c176c1c1748bb02745fc1191b/urdf/ergoCub/robots/ergoCubSN001/model.urdf#L3262-L3275

**Comment by AntonioConsilvio** [comment]
Hi @Nicogene @pattacini, I think there was a little misunderstanding. The FTs on the shoulders have been disabled from configuration files due to malfunctioning, so the sensors should be removed from the URDF to be compatible with the configuration files.

**Comment by pattacini** [comment]
Ok thanks @AntonioConsilvio for the heads-up 👍🏻 
I've update the OP and the title accordingly.

**Comment by Nicogene** [comment]
@GiulioRomualdi do you need this change in `ergoCubSN001` or/and `ergoCubGazeboV1` urdf?

**Comment by Nicogene** [comment]
PR:

- #206

**Comment by GiulioRomualdi** [comment]
> @GiulioRomualdi do you need this change in `ergoCubSN001` or/and `ergoCubGazeboV1_1` urdf?

Sorry, I completelly missed the message :( 
We need to remove them from `ergoCubSN001` no need from `ergoCubGazeboV1_1`

**Comment by Nicogene** [comment]
> > @GiulioRomualdi do you need this change in `ergoCubSN001` or/and `ergoCubGazeboV1_1` urdf?
> 
> Sorry, I completely missed the message :( We need to remove them from `ergoCubSN001` no need from `ergoCubGazeboV1_1`

I am afraid that I have to remove it also from `ergoCubGazeboV1_1` since I have to remove the nws for those ft from the xml that is common between all the models.

But if the model `ergoCubSN001` is used without launghing the yarprobotinterface plugin I can remove them only from that urdf an keep the ergocub.xml unchanged.

cc @traversaro

**Comment by GiulioRomualdi** [comment]
In this case i think we should update wbd  xml file. Are there 2 separate files for gazebov1 and gazebov1_1?

**Comment by traversaro** [comment]
Related to https://github.com/robotology/whole-body-estimators/issues/32, that should simplify doing this.

**Comment by Nicogene** [comment]
> In this case i think we should update wbd xml file. Are there 2 separate files for gazebov1 and gazebov1_1?

Unfortunately not, it was not needed until now, but I would avoid adding an xml file for this temporary situation
