### ISSUE TITLE
[ergoCubGazeboV1_1] Mismatch between left and right arm controlbaords 

### ISSUE THREAD

**Issue by GiulioRomualdi** [icub-tech-iit/ergocub-software#218]
## Task description
I noticed the name of the plugin used for the left arm is `controlboard_left_arm_no_hand` while the one of the `right` arm is called `controlboard_right_arm` is this wanted?

## Definition of Done
Clarify if the two names are correct. If not we should fix the mismatch

**Comment by Nicogene** [comment]
I think is a leftover/copy paste, the "correct" one should be `controlboard_right_arm_no_hand` since that controlboard is controlling the arm until the wrist
