### ISSUE TITLE
Add ergoCub SN002 + ergoCubGazeboV1_2 (?) urdf

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/ergocub-software#228]
## Task description
Since `ergoCub` SN002 is close to being delivered we need the urdf of the new robot. Respect SN001 from the urdf side it should be identical, the only difference is in the head's weight.
Probably the version will be increased to V1_2, we need to update also the gazebo models.

## Definition of Done
The new urdfs have been added.

cc @pattacini @maggia80

**Comment by pattacini** [comment]
cc @Fabrizio69

**Comment by Nicogene** [comment]
Adding it should be easier, see:

- https://github.com/icub-tech-iit/ergocub-software/issues/235#issuecomment-2061350998

**Comment by Nicogene** [comment]
First step:
- https://github.com/icub-tech-iit/ergocub-software/pull/241

**Comment by Nicogene** [comment]
See:
- https://github.com/icub-tech-iit/ergocub-software/pull/242
