### ISSUE TITLE
ergoCubSN002 model missing

### ISSUE THREAD

**Issue by GiulioRomualdi** [icub-tech-iit/ergocub-software#239]
## Task description
Today ergoCubSN002 was released however the model is not available. I think it is similar to ergoCUbSN001

## Definition of Done
Having the model in the repo cc @Nicogene and @traversaro

**Comment by Nicogene** [comment]
> Today ergoCubSN002 was released however the model is not available. I think it is similar to ergoCUbSN001

Yes probably only the assignedMass and `assignedInertia` has to be changed for `head` link.

Isn't it this issue a duplication of #228 ?

**Comment by GiulioRomualdi** [comment]
> Isn't it this issue a duplication of https://github.com/icub-tech-iit/ergocub-software/issues/228 ?

Ops my fault! I'm sorry for that :(

**Comment by Nicogene** [comment]
> > Isn't it this issue a duplication of #228 ?
> 
> Ops my fault! I'm sorry for that :(

No problem!
