### ISSUE TITLE
wrist's joints: getRefPosition() returns a value that differs from setPosition()

### ISSUE THREAD

**Issue by PasMarra** [icub-tech-iit/ergocub-software#261]
If I set a position with `yarp::dev::IPositionDirect::setPosition()` and then I call `yarp::dev::IPositionDirect::getRefPosition()`, I get the same value, as I expect, for all the joints but the wrist's ones.

As an example, in the image below you can see what happens with the `wrist_pitch`:
- Traj/Des is what I set with `yarp::dev::IPositionDirect::setPosition()`
- PID/Ref  is what I read with `yarp::dev::IPositionDirect::getRefPosition()`

![image](https://github.com/user-attachments/assets/2f98db96-ff7f-41c3-ba4c-aa734fdca50d)

It is important to notice that this problem does not appear in simulation.

**Comment by ale-git** [comment]
I think that the problem is here, where the special case of wrist kinematics isn't managed in reading:
https://github.com/robotology/icub-firmware/blob/fa7f652528f9aa2cee32c4028e8c9256aef23da0/emBODY/eBcode/arch-arm/embobj/plus/mc/Controller.c#L1509

as it is managed in writing:
https://github.com/robotology/icub-firmware/blob/fa7f652528f9aa2cee32c4028e8c9256aef23da0/emBODY/eBcode/arch-arm/embobj/plus/mc/Controller.c#L1557

**Comment by pattacini** [comment]
We will prepare a patch for that.

**Comment by Nicogene** [comment]
> It is important to notice that this problem does not appear in simulation.

For the records, in simulation the wrist has not any coupling involved, it is composed by the relative serial mechanism

**Comment by ale-git** [comment]
https://github.com/robotology/icub-firmware/pull/522

This PR should fix the problem. Needs to be tested.

**Comment by vigisushrutha23** [comment]
Is the PR ready for testing on the robot.? If so I could help with the testing tomorrow from 11, when I have the slot on EcubSN001.

**Comment by ale-git** [comment]
Hi @vigisushrutha23, I'll prepare the binary .hex in the evening. It is already functionally tested, in fact this version (2.9) is already running in SN001 wrists if nobody has flashed other versions in the meanwhile. The remaining test to do is to check if it solves the target feedback mismatch.

**Comment by ale-git** [comment]
Hi @vigisushrutha23, this is the draft PR with amc.hex wrist firmware

https://github.com/robotology/icub-firmware-build/pull/167

**Comment by vigisushrutha23** [comment]
@Nicogene Sorry I forgot to update here. We were not able to run experiments yesterday due to network issues. @PasMarra and I will run tests tomorrow as the network issue has been solved during my reserved slot from 10-1

**Comment by PasMarra** [comment]
**Signals recap**

- `meas_or_ref` is a boolean: 1 => trajectory initialized from `yarp::dev::IEncoders::getEncoder()`; 0 => trajectory initialized from `yarp::dev::IPositionDirect::getRefPosition()`;
- `Traj/Ini` is the initial value for the trajectory, according to the previous variable;
- `ENC/meas` is what I read with `yarp::dev::IEncoders::getEncoder()`;
- `Traj/Des` is what I set with `yarp::dev::IPositionDirect::setPosition()`.

That said, if `yarp::dev::IPositionDirect::setPosition()` is equal to `yarp::dev::IPositionDirect::getRefPosition()`, then when `meas_or_ref` goes to zero there is no variation in `Traj/Des`, i.e. it appears to be a continuous signal.
**So, I would say that it works fine now.**

# Left wrist

<details><summary>Roll</summary>

![Image](https://github.com/user-attachments/assets/0a0acc6f-3c17-451c-bce0-b69fc6331a4d)

</details>


<details><summary>Pitch</summary>

![Image](https://github.com/user-attachments/assets/5f575b12-0660-4707-bd75-965fbcbb18e4)

</details>



<details><summary>Yaw</summary>

![Image](https://github.com/user-attachments/assets/a3e54b0f-8d9e-459e-80ed-5540c5b67733)

</details>


# Right wrist


<details><summary>Roll</summary>

![Image](https://github.com/user-attachments/assets/0c2aa574-6ac7-41d8-8b23-aa015188dd3f)

</details>


<details><summary>Pitch</summary>

![Image](https://github.com/user-attachments/assets/f33be126-c335-4d3d-af44-de88c3602b30)

</details>



<details><summary>Yaw</summary>

![Image](https://github.com/user-attachments/assets/ca230181-ca19-430d-bb4b-3bcf140d54e4)

</details>

**Comment by PasMarra** [comment]
Anyway, there is also another problem with some joints. As you can see from the video below, there is a small jump during the motion of the wrist:

 https://github.com/user-attachments/assets/9a897959-ddb8-4242-ab38-da2a97dabb91

https://github.com/user-attachments/assets/c2352417-235e-4c90-91b5-c4b96d09139d

https://github.com/user-attachments/assets/9e01f84b-11fb-4a79-9ff1-ef0e71db955a


Notice that this jump does not seem to appear in the any of the plots above.
