### ISSUE TITLE
Shall release ergocub-software and include in the robotology-superbuild?

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/ergocub-software#31]
For the robotology-superbuild obviously the generation of the model will not enabled acting like `icub-models`

cc @traversaro @pattacini

**Comment by pattacini** [comment]
I would say so.

**Comment by traversaro** [comment]
As long as the repo remains small enough, we could even include it in the core profile, otherwise we need to identify or add a new profile in which to add it.

**Comment by Nicogene** [comment]
First release done: https://github.com/icub-tech-iit/ergocub-software/releases/tag/v0.1.0

**Comment by Nicogene** [comment]
PR merged, closing
