### ISSUE TITLE
Left shoulder yaw and camera tilt not coherent between robot and model

### ISSUE THREAD

**Issue by lrapetti** [icub-tech-iit/ergocub-software#47]
Today @GiulioRomualdi and @mebbaid spotted that there is a mismatch in the direction of the shoulder yaw joint and the camera tilt between the model and the robot. 

This was spotted comparing the motion in Gazebo and the real robot when increasing the value of the joint from `yarpmotorgui`.

Here for example is the comparison for the shoulder:

https://user-images.githubusercontent.com/35487806/217552978-82aedd43-ec9c-40c4-9bbd-cacecf55c1bd.mp4

All the other joints have been checked and are coherent.

cc @pattacini @Nicogene @sgiraz

**Comment by pattacini** [comment]
Thanks heaps for reporting!

**Comment by pattacini** [comment]
Hi @mfussi66,

We need first to understand what is the intended correct direction of the rotation and then fix either the robot XML file or the URDF.

**Comment by mfussi66** [comment]
> We need first to understand what is the intended correct direction of the rotation and then fix either the robot XML file or the URDF.

By checking within Gazebo, that the URDF needs changing. The camera should tilt upwards with a positive angle, to be consistent with the head pitch.

**Comment by pattacini** [comment]
> to be consistent with the head pitch.

True.

Sorry for being nitpicking but what is the direction of movement of the iCub eyes with respect to the head pitch? Just to understand our "heritage".

**Comment by mfussi66** [comment]
> Sorry for being nitpicking but what is the direction of movement of the iCub eyes with respect to the head pitch? Just to understand our "heritage".

In Gazebo iCub3 moves neck pitch and eyes tilt in opposite directions, see:

![image](https://user-images.githubusercontent.com/38140169/217793693-cb4ed278-d094-48a4-8a94-bc49b4818e02.png)

Not sure if it's the same on the robot.

**Comment by mfussi66** [comment]
Regarding the shoulder yaw, I think that also needs a fix at the URDF level, since the iCub3 Gazebo model is consistent with the real ergoCub (assuming Gazebo iCub3 and real iCub3 are consistent between each other).

**Comment by pattacini** [comment]
> > Sorry for being nitpicking but what is the direction of movement of the iCub eyes with respect to the head pitch? Just to understand our "heritage".
> 
> In Gazebo iCub3 moves neck pitch and eyes tilt in opposite directions, see:
> Not sure if it's the same on the robot.

Thanks for checking 👍🏻 
The physical iCub 2.x is aligned with iCub in Gazebo as there's a number of software working on both the domains correctly.

Just an example:
- https://github.com/vvv-school/assignment_make-it-roll

This doesn't mean that we need to copy out the same directions on ergoCub though.
