### ISSUE TITLE
Face expression stopped to work

### ISSUE THREAD

**Issue by lrapetti** [icub-tech-iit/ergocub-software#49]
In order to enable wbd on `ergocub-torso`, we have installed the robotology-superbuild dependencies using the [`install_apt_dependencies.sh`](https://github.com/robotology/robotology-superbuild/blob/master/scripts/install_apt_dependencies.sh) script. While doing this, however, the following message was raised:
![photo1675931605](https://user-images.githubusercontent.com/35487806/217758978-eff2a35e-90cc-4e8b-bf7b-d85b535a79eb.jpeg)
we continued, but after a while we realized the face expressions stopped to work (I guess it was the service that was supposed to be restarted). After restarting the robot motors and CPU, the face expression seems to be still off:
![photo1675931605](https://user-images.githubusercontent.com/35487806/217759259-1600559e-2f99-45da-9a43-0b474d905b9d.jpeg)

cc @GiulioRomualdi @mebbaid

**Comment by lrapetti** [comment]
cc @Nicogene @pattacini 

Let us know if this is the right place to open this kind of issues, or if you prefer them to be opened in https://github.com/robotology/icub-tech-support/issues/

**Comment by Nicogene** [comment]
By the way the oled screen is attached to ergocub-head, it may be possible that the screen stopped working independently what you did on ergocub-torso

**Comment by pattacini** [comment]
>At the same time, we can open an issue here for what regards the development of a SW layer to deal with the OLED.

See https://github.com/icub-tech-iit/ergocub-software/issues/50.

Closing then.
