### ISSUE TITLE
Add white diffuse color to the robot links for proper visualization in Modern Gazebo simulator

### ISSUE THREAD

**Issue by paolo-viceconte** [icub-tech-iit/ergocub-software#75]
When trying to visualize the ergoCub model in Ignition Gazebo, the robot is visualized all in white:

![no_diffuse](https://user-images.githubusercontent.com/41757826/224044801-0bd0845b-53dd-4da6-aaed-519bf4cdad0b.png)

This is instead the result if a white diffuse color is applied to all the robot links:

![diffuse](https://user-images.githubusercontent.com/41757826/224045768-437127cc-f0a9-416b-8e14-ccd0656825e3.png)

The lines added to the urdf model to get the above can be found [here](https://github.com/paolo-viceconte/paper_viceconte_2021_ral_adherent/blob/4b250e5e519324ea6ec8ea720885268574672678/src/adherent/model/ergoCubGazeboV1_xsens/ergoCubGazeboV1_xsens.urdf#L3410-L3871).

This issue is to track the possibility of including these changes in the ergoCub urdf, since they can be of interest for future development in Ignition Gazebo.

cc @traversaro @S-Dafarra @GiulioRomualdi

**Comment by Nicogene** [comment]
I don't think it is possible to add it right now, I check `simmechanics-to-urdf` but there is not any option that handles visual, @traversaro correct me if I am wrong.
I would open an issue there for adding this feature, even if we are working on creating our own creo2urdf converter

**Comment by paolo-viceconte** [comment]
Closing this for the time being, since it could be just related to a specific development setup. We will reopen it if it appears to be a more general issue.
