### ISSUE TITLE
Missing SCSYS in the fingertip

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/ergocub-software#9]
The scsys of the fingertip seems not being exported in the urdf, they have to be added in the yml for being exported

They are called `SCSYS_*_SKIN_TAXEL_*`

![immagine](https://user-images.githubusercontent.com/19152494/209119986-d5603bce-d7e4-427d-9f0f-b415362afb88.png)

cc @Lawproto

**Comment by Lawproto** [comment]
cc @fiorisi
