### ISSUE TITLE
Align xml files of legs/foot FTs for using multipleanalogsensorsremapper

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/ergocub-software#97]
This is required for aligning the simulated robots with the real one after: https://github.com/robotology/robots-configuration/issues/485

cc @pattacini

**Comment by traversaro** [comment]
I think that also the one in the arm need to be aligned, as their prefix is `/<robotPortPrefix>/<part>` and not `/<robotPortPrefix>/<part>/FT`.

**Comment by Nicogene** [comment]
Fixed by https://github.com/icub-tech-iit/ergocub-software/pull/123
